### ISSUE TITLE
Does Not Install

### ISSUE THREAD

**Issue by edsonayllon** [RadarTech/sdk#59]
The following error is output during installation:

```
../hidapi/libusb/hid.c:47:10: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [hidapi.target.mk:103: Release/obj.target/hidapi/hidapi/libusb/hid.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/workspace/fulcrum_ui/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-1028-gcp
gyp ERR! command "/home/gitpod/.nvm/versions/node/v10.15.3/bin/node" "/workspace/fulcrum_ui/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/workspace/fulcrum_ui/node_modules/ledgerco/node_modules/node-hid/build/Release/HID.node" "--module_name=HID" "--module_path=/workspace/fulcrum_ui/node_modules/ledgerco/node_modules/node-hid/build/Release"
gyp ERR! cwd /workspace/fulcrum_ui/node_modules/ledgerco/node_modules/node-hid
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
```

**Comment by dchambers** [comment]
> Works with certain versions of Node.js

Thanks for the hint, downgrading from Node.js `10.x` to `8.x` did it for me 👍
